language: go
go:
- '1.12'
env:
- GO111MODULE=on
script:
- make test
notifications:
  slack:
    secure: luG1SDmkYTa5m67NQnSf+otGLqiPwqQ6P+mdy0CZclcrU51x3G03CKS0sAunWVPYte0NOr+5/qoB+LgJRq4+ZbOjA2GZvGG40GN+Gv8HJXlpyp6SlL8uca5c8t0JLNHESR3MrahxetLCgSk/N8KxS+VXF03XdpGa+q2ldwspQABn3pKjrqHP82t636gvMhR7gERpfqLpYg+XMFCGm/WvfjnHzxjKW6T6lB+lFetcFemXFJZedQRDFWDKFkgVXCaSgXIa6ELUPc4giWIzCh2QiAk01ISJZmhThplucZo9SDoQWuMXULVoJMj75oh6NGHidEFZB9+EjVd0c+3Rw/pdjl0F4fUrQVTmvnv3x9A6muo68LWhk7MRNl3FP0Jvj3zpoOO+/1jfArepxIj0qdsnJwP5rm6hyI/eRvWJxmHSSKMsK0YkKAuo7tRLNELVSIY71BlR0fbxnSk4oH+wYbgLLh9eBU1La94PbU4PVyU7ix4EK/Zv/pSR3F0To3m/wkHmDeh2Qk2LKxZbwszltef0tR9XQ1FZw2HGoSKExGsVPWOswGH96h0uErTOC9HpNOI7iByV4QsQJl/Gh97l6hffT6jrKv3MFF5Dzr7C86rsY7K147jqRlQsyGFn6vx4TNIhB5y6joZ8qCN8HhQx8o57CXkmxZvdN3q9vtvgix+BXuQ=
