name: Run Acceptance Tests
on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  run-acc-tests:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    env:
      VAULT_AUTH_ACC_TEST_ROLE_ARN: ${{ secrets.VAULT_AUTH_ACC_TEST_ROLE_ARN }}
      VAULT_AUTH_ACC_TEST_ACCESS_KEY_ID: ${{ secrets.VAULT_AUTH_ACC_TEST_ACCESS_KEY_ID }}
      VAULT_AUTH_ACC_TEST_SECRET_KEY: ${{ secrets.VAULT_AUTH_ACC_TEST_SECRET_KEY }}
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
    - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      with:
        go-version-file: .go-version
        cache: true
    - name: Run Acceptance Tests
      run: make testacc
