name: Run Acceptance Tests
on:
  push:

permissions:
  contents: read

jobs:
  run-acc-tests:
    runs-on: ubuntu-latest
    env:
      VAULT_ACC_TEST_ROLE_ARN: ${{ secrets.VAULT_ACC_TEST_ROLE_ARN }}
      VAULT_ACC_TEST_ACCESS_KEY_ID: ${{ secrets.VAULT_ACC_TEST_ACCESS_KEY_ID }}
      VAULT_ACC_TEST_SECRET_KEY: ${{ secrets.VAULT_ACC_TEST_SECRET_KEY }}
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version-file: .go-version
        cache: true
    - name: Run Acceptance Tests
      run: make testacc
