name: Run Acceptance Tests
on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  run-acc-tests:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    env:
      VAULT_AUTH_ACC_TEST_ROLE_ARN: ${{ secrets.VAULT_AUTH_ACC_TEST_ROLE_ARN }}
      VAULT_AUTH_ACC_TEST_ACCESS_KEY_ID: ${{ secrets.VAULT_AUTH_ACC_TEST_ACCESS_KEY_ID }}
      VAULT_AUTH_ACC_TEST_SECRET_KEY: ${{ secrets.VAULT_AUTH_ACC_TEST_SECRET_KEY }}
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version-file: .go-version
        cache: true
    - name: Run Acceptance Tests
      run: make testacc
